#!/bin/bash

show_help() {
    local topic=$1
    
    if [ -z "$topic" ]; then
        echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
        echo -e "${BLUE}║ ${WHITE}RUPP-CLI HELP                                         ${BLUE}║${NC}"
        echo -e "${BLUE}╠════════════════════════════════════════════════════════╣${NC}"
        echo -e "${BLUE}║ ${CYAN}Usage: rupp-cli COMMAND [OPTION]                       ${BLUE}║${NC}"
        echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${YELLOW}Commands:${NC}                                              ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  status${NC}      - Show system security status             ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  audit${NC}       - Run security audit                      ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  firewall${NC}    - Manage firewall settings                ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  selinux${NC}     - Manage SELinux configuration            ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  ssh${NC}         - Configure SSH hardening                 ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  ids${NC}         - Manage intrusion detection system       ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  updates${NC}     - Manage system updates                   ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  harden${NC}      - Apply one-click hardening (basic/medium/high) ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  help${NC}        - Show help for specific command          ${BLUE}║${NC}"
        echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${YELLOW}Examples:${NC}                                              ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  rupp-cli status${NC}                                  ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  rupp-cli firewall enable${NC}                         ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  rupp-cli ssh disable-root${NC}                        ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  rupp-cli harden medium${NC}                           ${BLUE}║${NC}"
        echo -e "${BLUE}║ ${GREEN}  rupp-cli help firewall${NC}                           ${BLUE}║${NC}"
        echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
    else
        case "$topic" in
            firewall)
                echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
                echo -e "${BLUE}║ ${WHITE}FIREWALL MANAGEMENT HELP                              ${BLUE}║${NC}"
                echo -e "${BLUE}╠════════════════════════════════════════════════════════╣${NC}"
                echo -e "${BLUE}║ ${CYAN}Usage: rupp-cli firewall COMMAND [OPTION]             ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Commands:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  status${NC}             - Show firewall status             ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  enable${NC}             - Enable firewall                  ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  disable${NC}            - Disable firewall                 ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  add-rule PORT PROTO${NC} - Add firewall rule               ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  remove-rule PORT PROTO${NC} - Remove firewall rule         ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  create-zone${NC}         - Create new zones                ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  check-zone${NC}         - Show active zones                ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  list-zones${NC}         - Show list zones                ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  check-services ZONE${NC} - List services in zone           ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  change-zone ZONE${NC}   - Change default zone              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  add-service ZONE SVC${NC} - Add service to zone            ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  remove-service ZONE SVC${NC} - Remove service from zone    ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Examples:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli firewall status${NC}                         ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli firewall add-rule 8080 tcp${NC}              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli firewall check-services public${NC}          ${BLUE}║${NC}"
                echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
                ;;
            selinux)
                echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
                echo -e "${BLUE}║ ${WHITE}SELINUX MANAGEMENT HELP                               ${BLUE}║${NC}"
                echo -e "${BLUE}╠════════════════════════════════════════════════════════╣${NC}"
                echo -e "${BLUE}║ ${CYAN}Usage: rupp-cli selinux COMMAND                       ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Commands:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  status${NC}     - Show SELinux status                     ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  enforcing${NC}  - Set SELinux to enforcing mode           ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  permissive${NC} - Set SELinux to permissive mode          ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  relabel${NC}    - Relabel system on next boot             ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Examples:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli selinux status${NC}                         ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli selinux enforcing${NC}                      ${BLUE}║${NC}"
                echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
                ;;
            ssh)
                echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
                echo -e "${BLUE}║ ${WHITE}SSH HARDENING HELP                                    ${BLUE}║${NC}"
                echo -e "${BLUE}╠════════════════════════════════════════════════════════╣${NC}"
                echo -e "${BLUE}║ ${CYAN}Usage: rupp-cli ssh COMMAND [OPTION]                  ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Commands:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  status${NC}        - Show SSH configuration               ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  disable-root${NC}  - Disable root login via SSH           ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  enable-root${NC}   - Enable root login via SSH            ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  change-port PORT${NC} - Change SSH port                   ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Examples:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ssh status${NC}                             ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ssh disable-root${NC}                       ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ssh change-port 2222${NC}                   ${BLUE}║${NC}"
                echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
                ;;
            ids)
                echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
                echo -e "${BLUE}║ ${WHITE}INTRUSION DETECTION HELP                               ${BLUE}║${NC}"
                echo -e "${BLUE}╠════════════════════════════════════════════════════════╣${NC}"
                echo -e "${BLUE}║ ${CYAN}Usage: rupp-cli ids COMMAND [OPTION]                   ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Commands:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  status${NC}       - Show fail2ban status                  ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  enable${NC}       - Enable fail2ban                       ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  disable${NC}      - Disable fail2ban                      ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  jail-status [JAIL]${NC} - Show jail status                ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  ban-ip IP JAIL${NC} - Ban an IP in a specific jail      ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  unban-ip IP JAIL${NC} - Unban an IP from a jail         ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Examples:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ids status${NC}                             ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ids enable${NC}                             ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ids disable${NC}                            ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ids jail-status sshd${NC}                   ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ids ban-ip 192.168.1.100 sshd${NC}          ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli ids unban-ip 192.168.1.100 sshd${NC}        ${BLUE}║${NC}"
                echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
                ;;
            updates)
                echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
                echo -e "${BLUE}║ ${WHITE}SYSTEM UPDATES HELP                                   ${BLUE}║${NC}"
                echo -e "${BLUE}╠════════════════════════════════════════════════════════╣${NC}"
                echo -e "${BLUE}║ ${CYAN}Usage: rupp-cli updates COMMAND                       ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Commands:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  check${NC}         - Check for available updates          ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  apply${NC}         - Apply all updates                    ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  security-only${NC} - Apply security updates only          ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  schedule${NC}      - Set up automatic updates             ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Examples:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli updates check${NC}                          ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli updates apply${NC}                          ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli updates schedule${NC}                       ${BLUE}║${NC}"
                echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
                ;;
            harden)
                echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
                echo -e "${BLUE}║ ${WHITE}SECURITY HARDENING HELP                               ${BLUE}║${NC}"
                echo -e "${BLUE}╠════════════════════════════════════════════════════════╣${NC}"
                echo -e "${BLUE}║ ${CYAN}Usage: rupp-cli harden LEVEL                          ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Levels:${NC}                                                ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  basic${NC}   - Basic security settings                    ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  medium${NC}  - Medium security settings                   ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  high${NC}    - High security settings                     ${BLUE}║${NC}"
                echo -e "${BLUE}║                                                        ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${YELLOW}Examples:${NC}                                              ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli harden basic${NC}                           ${BLUE}║${NC}"
                echo -e "${BLUE}║ ${GREEN}  rupp-cli harden medium${NC}                          ${BLUE}║${NC}"
                echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
                ;;
            *)
                echo -e "${RED}Error: Unknown help topic '$topic'${NC}"
                echo -e "Run 'rupp-cli help' for a list of available commands."
                ;;
        esac
    fi
}
